TAGS = [
    # DISEASES
    {"label": "DISEASE", "pattern": "depression"},
    {"label": "DISEASE", "pattern": "anxiety disorder"},
    {"label": "DISEASE", "pattern": "bipolar disorder"},
    {"label": "DISEASE", "pattern": "schizophrenia"},
    {"label": "DISEASE", "pattern": "obsessive-compulsive disorder"},
    {"label": "DISEASE", "pattern": "post-traumatic stress disorder"},
    {"label": "DISEASE", "pattern": "eating disorder"},
    {"label": "DISEASE", "pattern": "narcolepsy"},
    {"label": "DISEASE", "pattern": "cancer"},
    {"label": "DISEASE", "pattern": "mental illness"},
    {"label": "DISEASE", "pattern": "addiction"},
    {"label": "DISEASE", "pattern": "drug abuse"},
    {"label": "DISEASE", "pattern": "mental abuse"},
    {"label": "DISEASE", "pattern": "chronically ill"},
    {"label": "DISEASE", "pattern": "terminally ill"},
    {"label": "DISEASE", "pattern": "borderline personality disorder"},
    {"label": "DISEASE", "pattern": "panic disorder"},
    {"label": "DISEASE", "pattern": "social anxiety disorder"},
    {"label": "DISEASE", "pattern": "generalized anxiety disorder"},
    {"label": "DISEASE", "pattern": "agoraphobia"},
    {"label": "DISEASE", "pattern": "anorexia"},
    {"label": "DISEASE", "pattern": "bulimia"},
    {"label": "DISEASE", "pattern": "binge eating disorder"},
    {"label": "DISEASE", "pattern": "adhd"},
    {"label": "DISEASE", "pattern": "attention deficit disorder"},
    {"label": "DISEASE", "pattern": "autism"},
    {"label": "DISEASE", "pattern": "dissociative identity disorder"},
    {"label": "DISEASE", "pattern": "ocd"},
    {"label": "DISEASE", "pattern": "seasonal affective disorder"},
    {"label": "DISEASE", "pattern": "insomnia disorder"},
    {"label": "DISEASE", "pattern": "substance use disorder"},
    {"label": "DISEASE", "pattern": "personality disorder"},
    {"label": "DISEASE", "pattern": "psychosis"},
    {"label": "DISEASE", "pattern": "schizoaffective disorder"},
    {"label": "DISEASE", "pattern": "body dysmorphic disorder"},
    {"label": "DISEASE", "pattern": "dysthymia"},
    {"label": "DISEASE", "pattern": "major depressive disorder"},
    {"label": "DISEASE", "pattern": "manic depression"},
    {"label": "DISEASE", "pattern": "paranoid personality disorder"},
    {"label": "DISEASE", "pattern": "phobia"},


    # SYMPTOMS
    {"label": "SYMPTOM", "pattern": "eating problems"},
    {"label": "SYMPTOM", "pattern": "paranoia"},
    {"label": "SYMPTOM", "pattern": "feeling crazy"},
    {"label": "SYMPTOM", "pattern": "nervous breakdown"},
    {"label": "SYMPTOM", "pattern": "burnout"},
    {"label": "SYMPTOM", "pattern": "mental health issues"},
    {"label": "SYMPTOM", "pattern": "struggling with my mind"},
    {"label": "SYMPTOM", "pattern": "trauma"},
    {"label": "SYMPTOM", "pattern": "anxious"},
    {"label": "SYMPTOM", "pattern": "depressed"},
    {"label": "SYMPTOM", "pattern": "mood swings"},
    {"label": "SYMPTOM", "pattern": "insomnia"},
    {"label": "SYMPTOM", "pattern": "fatigue"},
    {"label": "SYMPTOM", "pattern": "tired"},
    {"label": "SYMPTOM", "pattern": "irritability"},
    {"label": "SYMPTOM", "pattern": "social withdrawal"},
    {"label": "SYMPTOM", "pattern": "lack of focus"},
    {"label": "SYMPTOM", "pattern": "stress"},
    {"label": "SYMPTOM", "pattern": "restlessness"},
    {"label": "SYMPTOM", "pattern": "freaking out"},
    {"label": "SYMPTOM", "pattern": "feeling down"},
    {"label": "SYMPTOM", "pattern": "can't sleep"},
    {"label": "SYMPTOM", "pattern": "burned out"},
    {"label": "SYMPTOM", "pattern": "tired all the time"},
    {"label": "SYMPTOM", "pattern": "on edge"},
    {"label": "SYMPTOM", "pattern": "trust issues"},
    {"label": "SYMPTOM", "pattern": "overthinking"},
    {"label": "SYMPTOM", "pattern": "emptiness"},
    {"label": "SYMPTOM", "pattern": "paranoid"},
    {"label": "SYMPTOM", "pattern": "struggling"},
    {"label": "SYMPTOM", "pattern": "suicidal"},
    {"label": "SYMPTOM", "pattern": "barely sleep"},
    {"label": "SYMPTOM", "pattern": "cannot stop thinking"},
    {"label": "SYMPTOM", "pattern": "exhausted"},
    {"label": "SYMPTOM", "pattern": "delusions"},
    {"label": "SYMPTOM", "pattern": "hopeless"},
    {"label": "SYMPTOM", "pattern": "hair loss"},
    {"label": "SYMPTOM", "pattern": "violent"},
    {"label": "SYMPTOM", "pattern": "desperate"},
    {"label": "SYMPTOM", "pattern": "socially isolated"},
    {"label": "SYMPTOM", "pattern": "emotional wreck"},

    # MEDICATIONS
    {"label": "MEDICATION", "pattern": "sertraline"},
    {"label": "MEDICATION", "pattern": "fluoxetine"},
    {"label": "MEDICATION", "pattern": "citalopram"},
    {"label": "MEDICATION", "pattern": "venlafaxine"},
    {"label": "MEDICATION", "pattern": "alprazolam"},
    {"label": "MEDICATION", "pattern": "diazepam"},
    {"label": "MEDICATION", "pattern": "clonazepam"},
    {"label": "MEDICATION", "pattern": "lithium"},
    {"label": "MEDICATION", "pattern": "bupropion"},
    {"label": "MEDICATION", "pattern": "risperidone"},
    {"label": "MEDICATION", "pattern": "quetiapine"},
    {"label": "MEDICATION", "pattern": "prozac"},
    {"label": "MEDICATION", "pattern": "xanax"},
    {"label": "MEDICATION", "pattern": "zoloft"},
    {"label": "MEDICATION", "pattern": "lexapro"},
    {"label": "MEDICATION", "pattern": "valium"},
    {"label": "MEDICATION", "pattern": "loraz"},
    {"label": "MEDICATION", "pattern": "antipsychotics"},
    {"label": "MEDICATION", "pattern": "medications"},
    {"label": "MEDICATION", "pattern": "lamictal"},
    {"label": "MEDICATION", "pattern": "mdma"},
    {"label": "MEDICATION", "pattern": "pill bottle"},
    {"label": "MEDICATION", "pattern": "speed"},

    # TREATMENTS
    {"label": "TREATMENT", "pattern": "cognitive behavioral therapy"},
    {"label": "TREATMENT", "pattern": "psychotherapy"},
    {"label": "TREATMENT", "pattern": "talk therapy"},
    {"label": "TREATMENT", "pattern": "dialectical behavior therapy"},
    {"label": "TREATMENT", "pattern": "meditation"},
    {"label": "TREATMENT", "pattern": "stress management"},
    {"label": "TREATMENT", "pattern": "family therapy"},
    {"label": "TREATMENT", "pattern": "group therapy"},
    {"label": "TREATMENT", "pattern": "therapy"},
    {"label": "TREATMENT", "pattern": "mindfulness"},
    {"label": "TREATMENT", "pattern": "breathing exercises"},
    {"label": "TREATMENT", "pattern": "journaling"},
    {"label": "TREATMENT", "pattern": "self-care"},
    {"label": "TREATMENT", "pattern": "hospital"},
    {"label": "TREATMENT", "pattern": "exercise"},
    {"label": "TREATMENT", "pattern": "visit psychiatrist"},
    {"label": "TREATMENT", "pattern": "acupuncture"},
    {"label": "TREATMENT", "pattern": "occupational therapist"},
    {"label": "TREATMENT", "pattern": "positive thinking"}
]